server:
  port: 8090

spring:
  mail:
    host: smtp.gmail.com #SMTP server endpoint for Gmail
    port: 587 # Port for STARTTLS (explicit TLS), Connection starts unencrypted → then upgraded to TLS
    username: contactkhan0007@gmail.com
    password: ${email_password}
    properties:
      mail:
        smtp: 
          auth: true # Enables SMTP authentication, Without this, Gmail will reject the connection
          starttls:
            enable: true # Enables STARTTLS handshake
          connectiontimeout: 5000 # Max time (ms) to establish TCP connection
          timeout: 5000 # Max time waiting for server response after request
          writetimeout: 5000 # Max time allowed to send data to server

  receiver:
      protocol: imaps
      host: imap.gmail.com
      port: 993
      username: contactkhan0007@gmail.com
      password: ${email_password}
      save-directory: "Attachment/"
